---
# This local action builds an image and pushes it to registries
name: "Clear Space in Ubuntu Latest Agressively"
author: "AWS Labs MCP"
description: "Clears space in Ubuntu latest images aggressively so GitHub Runner has a less chance from running out of space"

# USAGE
#
# - id: clear-space
#   uses: ./.github/actions/clear-space-ubuntu-latest-agressively
# - name: Step to demonstrate how to access outputs (no need for this)
#   id: echo-output
#   run: |
#     echo "before: ${BEFORE}"
#     echo "after: ${AFTER}"
#   env:
#     BEFORE: ${{ steps.clear-space.outputs.before}}
#     AFTER: ${{ steps.clear-space.outputs.after}}

branding:
  # https://feathericons.com/
  icon: 'activity' # for shipping container ¯\_(ツ)_/¯
  color: 'yellow'

outputs:
  after:
    description: 'Space after clearing'
    value: ${{ steps.after.outputs.space }}
  before:
    description: 'Space before clearing'
    value: ${{ steps.before.outputs.space }}

runs:
  using: "composite"
  steps:
    - name: Space Before
      id: before
      run: |
        df -h
        du -h -k -d 1
        echo space="$(df --output=avail . | grep -v Avail)" >>"$GITHUB_OUTPUT"
      shell: bash
    - name: Clear Up Space (Agressively) to Minimize Chances of Running Out of Space
      shell: bash
      run: |
        sudo rm -rf \
          /usr/local/lib/android \
          /usr/share/dotnet \
          /opt/ghc \
          /usr/local/.ghcup \
          /usr/local/share/powershell \
          /usr/share/swift \
          /usr/lib/jvm || true

        printWarningMessage () {
          echo "[warning] Failed to remove '$1', perhaps because it doesn't exist. Ignoring..."
        }

        # Remove large packages we don't use.
        sudo apt list --installed

        sudo apt-get remove -y '^mysql-.*' || printWarningMessage '^mysql-.*'
        sudo apt-get remove -y '^dotnet-.*' --fix-missing || printWarningMessage '^dotnet-.*'
        sudo apt-get remove -y 'php.*' --fix-missing || printWarningMessage 'php.*'
        sudo apt-get remove -y '^mongodb-.*' --fix-missing || printWarningMessage '^mongodb-.*'
        sudo apt-get remove -y '^llvm-.*' --fix-missing || printWarningMessage '^llvm-.*'
        sudo apt-get remove -y google-cloud-sdk --fix-missing || printWarningMessage 'google-cloud-sdk'
        sudo apt-get remove -y google-cloud-cli --fix-missing || printWarningMessage 'google-cloud-cli'
        sudo apt-get autoremove -y >/dev/null 2>&1
        sudo apt-get autoclean -y >/dev/null 2>&1

        df -h
        du -h -k -d 1

    - name: Space After
      id: after
      run: |
        df -h
        du -h -k -d 1
        echo space="$(df --output=avail . | grep -v Avail)" >>"$GITHUB_OUTPUT"
      shell: bash
