---
# This workflow is to prevent unintentional merges that cannot be accomplished by rulesets or other settings.
name: Merge Prevention
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

permissions: {}

env:
  DO_NOT_MERGE_LABEL: hold-merging

jobs:
  fail-by-label:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: When PR has the "${{ env.DO_NOT_MERGE_LABEL }}" label
        id: pr-has-label
        if: contains(github.event.pull_request.labels.*.name, env.DO_NOT_MERGE_LABEL)
        run: |
          echo "The label \"${{ env.DO_NOT_MERGE_LABEL }}\" is used to prevent merging. When removed, this step will be skipped."
          cat << EOF > results.sarif
          {
            "version": "2.1.0",
            "\$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.4.json",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "${{ github.workflow }}"
                  }
                },
                "results": [
                  {
                    "ruleId": "MERGE-PREVENTION-001",
                    "level": "error",
                    "message": {
                      "text": "${{ env.DO_NOT_MERGE_LABEL }}"
                    },
                    "locations": [
                      {
                        "physicalLocation": {
                          "artifactLocation": {
                            "uri": "${{ github.sha }}"
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
          exit 1
      - name: When PR does not have the "${{ env.DO_NOT_MERGE_LABEL }}" label
        id: pr-missing-label
        if: ! github.event.pull_request.labels || ! contains(github.event.pull_request.labels.*.name, env.DO_NOT_MERGE_LABEL)
        run: |
          echo "The label \"${{ env.DO_NOT_MERGE_LABEL }}\" is absent, should succeed."
          cat << EOF > results.sarif
          {
            "version": "2.1.0",
            "\$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.4.json",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "${{ github.workflow }}"
                  }
                },
                "results": []
              }
            ]
          }
          EOF
          exit 0
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: success() || failure()
        with:
          name: results.sarif
          path: results.sarif
          if-no-files-found: error
      - uses: github/codeql-action/upload-sarif@57eebf61a2246ab60a0c2f5a85766db783ad3553 # v3.28.15
        if: success() || failure()
        with:
          sarif_file: results.sarif
