name: Scanners

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:

  secrets-scanner:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
      with:
        python-version: '3'
    - run: |
        pip install --require-hashes --requirement .github/workflows/detect-secrets-requirements.txt
    - name: detect-secrets
      id: detect-secrets
      run: | # pragma: allowlist secret
        detect-secrets scan --baseline .secrets.baseline
        cat .secrets.baseline | jq '[.results|to_entries|.[].value[]|{ "filename": .filename, "is_secret": .is_secret } | if .is_secret == null or .is_secret == true then .filename else empty end]|unique|if length>0 then error("potential secrets in: \(.)") else empty end'
